### ISSUE TITLE
Add database for available trainings

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1003]
We have to store a list of available trainings in the database. In the frontend, it should be possible to create and delete a trainings for administrators. A training consists of: 

- Name
- Description
- Required tools
- Git repository

**Comment by amolenaar** [comment]
We can probably define a "Training" project and have a couple of modules (models) in there. We can give each model a big "Play" button, to make it easy to start a training environent.

I envision the "database" to be a couple of git repos.

**Comment by MoritzWeber0** [comment]
> We can probably define a "Training" project and have a couple of modules (models) in there. We can give each model a big "Play" button, to make it easy to start a training environment.
> 
> I envision the "database" to be a couple of git repos.

I'd say that we have one Git repository for a training, not many per training. Also, modules could be handled by the training itself (for example, one Jupyter notebooks for each module). The Play button would be located on the training itself then.

**Comment by MoritzWeber0** [comment]
No longer needed due to https://github.com/DSD-DBS/capella-collab-manager/issues/1004#issuecomment-1770879834.
