### ISSUE TITLE
Initialize training setup, spawn related sessions

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1004]
It has to be possible to start a training: 

1. Spawn the sessions for all defined required tools
2. Initialize the sessions with the linked Git repository (clone the Git repository)
3. Open the session in the "training mode" viewer with pre-defined layout

**Comment by vik378** [comment]
one quick comment re no persistence required for training - you may want to save your progress and come back to it next day so it would be nice if we could figure something for it

**Comment by MoritzWeber0** [comment]
This should be covered by this paragraph:

> There should be a check-box if the pre-provisioned workspace should be persistent or not. [...] If the check-box is selected, the linked Git repositories of the models are loaded in the user's persistent volume. In training mode, non persistent workspaces are not allowed. There will be no check-box for training projects.

To clarify it: When spawning a pre-provisioned workspace for a training project, there will be no option to request a read-only workspace. Instead, the workspace is always persistent to prevent data loss.
