### ISSUE TITLE
Add documentation how to properly upload images to a Capella/T4C model

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1006]
There are some conditions and some things to avoid when uploading an image into a workspace. 

to add images to a remote TeamForCapella model, you have to execute these steps: 

1. Upload the image(s) into your session workspace
2. Right-click on the aird file, then select "Manage Images from Remote Server" 
3. Expand the project on the left site, open the "images" directory.
4. Click "Upload" on the right side.
5. Click "Select local images"
6. You workspace should be displayed. Select the uploaded images.
7. If it doesn't display your workspace, navigate to "Other locations" -> "Computer" -> "workspace"
8. In the description editor, you should be able to see new image when clicking on "Add image".

@jamilraichouni knows also a few tricks. The assignee of this ticket should have a short chat with him.

**Comment by vik378** [comment]
@MoritzWeber0 , not every instance may have dbs-ref ;-)
