### ISSUE TITLE
Branch selection in create-readonly-session isn't working

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-collab-manager#1072]
When requesting a Readonly session from a Project, one can choose the `Branch, tag or revision*`. This has no effect to the session. After connecting to it, the user is greeted by the model on the main branch.

**Comment by amolenaar** [comment]
Looks like it's not picked up from the frontend. From the k8s manifest:

```
    - name: GIT_REPOS_JSON
      value: '[{"url": "https://github.com/DSD-DBS/py-capellambse", "revision": "master",
        "depth": 1, "entrypoint": "/tests/data/melodymodel/6_0/Melody Model Test.aird",
        "nature": "model"}]'
```
