### ISSUE TITLE
Add resources to configuration of tools in the core settings

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-collab-manager#1136]
Every tool has its own requirements of resources. Currently the resource requirements are hardcoded and there are only 2 options for low and high limit. The ability to configure the `V1ResourceRequirements` needs to be added to the tool configuration.

**Comment by MoritzWeber0** [comment]
Related to https://github.com/DSD-DBS/capella-collab-manager/issues/1158
