### ISSUE TITLE
Cannot middle-click links at the top of the page

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capella-collab-manager#1164]
When middle-clicking one of the links at the top (Projects, Sessions, Session Viewer, etc.), nothing happens. Middle-clicking should open the link in a new tab, just like every other link.

**Comment by MoritzWeber0** [comment]
Thanks for reporting this. @romeonicholas can you have look into it?

**Comment by romeonicholas** [comment]
I'm pretty sure this is a 1 line fix--currently the routerLink is set on the div _outside_ the nav buttons, which is fine for just loading the page in place but messes up anchor-specific event handling. Moving the routerLink inside the anchor seems to fix it for me, but I'll test it further and submit a PR if I don't see any new bugs as a result.
