### ISSUE TITLE
File upload improvements

### ISSUE THREAD

**Issue by henrik429** [DSD-DBS/capella-collab-manager#118]
- [x] Iterate through tree more efficient (e.g. along a path instead of the current brute force approach) for functions `addFileToTree` and `removeFileFromTree`
- [x] Save all expanded nodes such that after adding/removing files (and therefore, after collapsing) they are expanded again all at once
- [x] Find a way to allow filenames with white spaces (instead of replacing them with underscores)
- [ ] Allow upload of files with sizes >100MB
- [ ] Use different icons for different file extensions

**Comment by MoritzWeber0** [comment]
- [ ] Adjust margins between folders and files (they are different)
- [ ] Set minimum width of upload files windows, so that it doesn't get wider when open 
- [ ] Mark directories without children as not expandable
