### ISSUE TITLE
Capella is slow on the ERTMS platform!

### ISSUE THREAD

**Issue by TheAugustinerGuy** [DSD-DBS/capella-collab-manager#122]
I would to like to bring to attention that I have been dealing with some serious slow moving Capella interface since the shift to ERTMS Platform. Previously, within the DB Platform as I was using the Virtual Desktop the things were running smoothly. 
For instance, it took me yesterday 30 mins from logging myself in, to adding a PAR fragment for an exchange scenario, and logging myself out.
To be more precise, 
1. The reaction time for the interface is slow i.e. it takes usually a couple of seconds to actually perform the action that was requested.  
2. The mouse clicks are usually not identified on the first click, rather you are needed to do an second click to make it work. 
3. Opening a session or an representation takes ages. 
4. In two weeks, I faced two auto disconnects (not because I was inactive, but due to some other reason) from the guacamole server. Which actually did not even occur once on the DB Platform.  

May be there are more. But for now, I rest my case! Thanks in advance for having a look at it.

**Comment by vik378** [comment]
@TheAugustinerGuy , let's have a short call to inspect your issue (I'll send an invite). In general ERTMS instance runs on Azure with AKS and has an autoscaler. So individual client pods have enough resource for Capella to feel happy. However we had similar report on the DB instance but we were able to nail that to a connectivity issue. We do suspect guacamole itself to have some resource issues at high loads so what would help to nail it is if you could somehow log the times when the thing gets slow for you and we will check it against cluster metrics.

**Comment by MoritzWeber0** [comment]
Hi @TheAugustinerGuy. Version 2 is now rolled out for some time. Did you have time to try it out? It would be nice to get some feedback if the situation improved with the update.
