### ISSUE TITLE
[Docs] Update Team for Capella Flow Documentation

### ISSUE THREAD

**Issue by micha91** [DSD-DBS/capella-collab-manager#1226]
The [documentation](https://dsd-dbs.github.io/capella-collab-manager/user/sessions/flows/t4c/) about importing Team for Capella projects seems to use outdated screenshots. In addition, it seems to be a bit redundant to me with this [documentation](https://capella.apps.dbcs-madrid.comp.db.de/docs/user/tools/capella/teamforcapella/import/import-from-t4c/).

Examples for outdated screenshots:
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/20923302/878f97d8-f69a-4668-a4c8-681d828b9e96)
vs.
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/20923302/a2cdfad7-d2f2-40e3-be9a-21fcc3c7aea6)

or

![image](https://github.com/DSD-DBS/capella-collab-manager/assets/20923302/10095357-5af4-43c5-a5f6-82a637d36aa4)
vs.
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/20923302/1b11434c-3fa2-4b8f-a571-be936cb19e02)

**Comment by Paula-Kli** [comment]
The two documentations are not redundant as importing a model is not immediately syncing back to T4C while `File` > `New` > `Other` but good that you asked! I made an information box on top of the page in order to make that clear
