### ISSUE TITLE
Standardize and move HTTP exceptions out of their routes

### ISSUE THREAD

**Issue by romeonicholas** [DSD-DBS/capella-collab-manager#1369]
In order to finish #883 we should agree on a standard format for exceptions we can enforce going forward. I've already removed the duplicated handler code in our exception files and made use of a base exception class, but I'd need some confirmation the new standard meets all our needs. Then I think it's probably worthwhile to also move the 80ish currently declared-in-route exceptions to exception files following this format as well, so everything gets properly registered and routes become a little easier to parse at a glance.

How does this look for a base class? (and how this looks in the OpenAPI docs)
```
@dataclasses.dataclass
class BaseError(Exception): #Wanted to avoid overriding "BaseException" but this could be called anything
    status_code: int        #Required for registering the HTTP exception
    title: str              #Appears as title in OpenAPI docs
    reason: str             #Could also be "detail"/"techincal"/something else
    err_code: str | None = None           #Not always present, how necessary is this?
    headers: dict[str, str] | None = None #Not always present, how necessary is this?
```
<img width="471" alt="OpenAPI exceptoin" src="https://github.com/DSD-DBS/capella-collab-manager/assets/79602065/3f85a3bb-8935-480b-b76c-d974382b914f">

**Comment by MoritzWeber0** [comment]
Documentation has to updated too: https://dsd-dbs.github.io/capella-collab-manager/development/backend/exception/

**Comment by MoritzWeber0** [comment]
LGTM

**Comment by romeonicholas** [comment]
Maybe? Probably? I think the hard part is that right now the error response generating function relies solely on the data inside the exception itself. We'd need a place to pass additional arguments, but it seems like it would be strange to keep that in the exception? Maybe not

**Comment by MoritzWeber0** [comment]
> Maybe? Probably? I think the hard part is that right now the error response generating function relies solely on the data inside the exception itself. We'd need a place to pass additional arguments, but it seems like it would be strange to keep that in the exception? Maybe not

Just define default values in the `__init__`, this should do it.
