### ISSUE TITLE
Session viewer: Allow selecting sessions that aren't ready yet

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capella-collab-manager#1518]
Currently the session viewer simply doesn't let you select a session that is still preparing. That's quite annoying at times, especially for the combination "Capella/Guacamole + Jupyter", since they start up very differently: Capella is quick to prepare, but takes some time after first connecting, while Jupyter takes much longer to prepare, but is there immediately when that's done.

It would be nice if I could select any session in the session viewer immediately, and when it's not ready yet I see a message similar to the sidebar card on the "Sessions" tab.

Quick mockup:

![grafik](https://github.com/DSD-DBS/capella-collab-manager/assets/1579756/9105e39c-734b-47e7-bd65-1dffe7742359)

(Is this even possible with the current setup and how sessions are handled?)

**Comment by MoritzWeber0** [comment]
> Is this even possible with the current setup and how sessions are handled?

Yes, that's certainly possible. The session state is already available in the session viewer, but it's not used. The main reason is the inadequate reliability of the session state. For example, there are cases where the session state jumps from "Session started" to "Preparation of session" -> The actual connection would happen to early. 

For better UX, I'd therefore implement https://github.com/DSD-DBS/capella-collab-manager/issues/1578 before addressing this issue.

**Comment by MoritzWeber0** [comment]
Implemented in https://github.com/DSD-DBS/capella-collab-manager/pull/1978.
