### ISSUE TITLE
Bootstrapping script errors out trying to push images to registry

### ISSUE THREAD

**Issue by zusorio** [DSD-DBS/capella-collab-manager#1536]
After going through all the steps to set this project up locally docker runs into an error when trying to push built images
```
➜  capella-collab-manager git:(main) DEVELOPMENT_MODE=1 make build helm-deploy open rollout
[...]
docker push k3d-myregistry.localhost:12345/capella/collab/backend
Using default tag: latest
The push refers to repository [k3d-myregistry.localhost:12345/capella/collab/backend]
Get "https://k3d-myregistry.localhost:12345/v2/": dialing k3d-myregistry.localhost:12345 container via direct connection because  has no HTTPS proxy: resolving host k3d-myregistry.localhost: lookup k3d-myregistry.localhost: no such host
```
This is happening both on macOS and Windows + WSL (Ubuntu 22.04).

**Comment by dominik003** [comment]
Hi @zusorio,
To me, it looks like you did not run `make create-cluster`, so the registry where the images should be pushed to does not exist yet. You can check if this registry exists by running `docker ps' and looking for the `registry:2' image. This container should also have the name `k3d-myregistry.localhost` and the following port `12345`, which is internally mapped to `5000`. 
If this is not the case, or if you have any other problems setting up the project locally, let me know.

**Comment by zusorio** [comment]
I had run `make create-cluster`, I just did it again to make sure I didn't miss it.
Docker is also showing the registry:
```
➜  capella-collab-manager git:(main) docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED       STATUS              PORTS                                                                                                       NAMES
6b32b3269a34   ghcr.io/k3d-io/k3d-proxy:5.6.3   "/bin/sh -c nginx-pr…"   2 hours ago   Up About a minute   0.0.0.0:443->443/tcp, 0.0.0.0:30000-30005->30000-30005/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:64473->6443/tcp   k3d-collab-cluster-serverlb
0d18e6b76764   rancher/k3s:v1.28.8-k3s1         "/bin/k3d-entrypoint…"   2 hours ago   Up About a minute                                                                                                               k3d-collab-cluster-server-0
e4d156d30f34   registry:2                       "/entrypoint.sh /etc…"   2 hours ago   Up About a minute   0.0.0.0:12345->5000/tcp                                                                                     k3d-myregistry.localhost
```

Despite that, I still get the same error message.

**Comment by MoritzWeber0** [comment]
Hi @zusorio,

First of all: Very cool that you are already dealing with the project. I love the motivation ❤️ 

In your case, the system can't resolve subdomains of localhost to `127.0.0.1`.

There are small packages, which add the functionality to resolve subdomains of localhost to localhost:

- On Debian/Ubuntu based systems, you can install [nss-myhostname](https://man7.org/linux/man-pages/man8/nss-myhostname.8.html) via `sudo apt install libnss-myhostname`. 
- On macOS, there is an alternative called `dnsmasq`. With homebrew you can install with `brew install dnsmasq`. Probably needs some additional configuration, haven't tried it out. 

Easier is the solution to modify the good old `/etc/hosts` file and add the following line: 
```
127.0.0.1 k3d-myregistry.localhost
```

Hope this helps!

**Comment by zusorio** [comment]
That fixed it! I made the mistake of only installing `nss-myhostname` inside the WSL container
