### ISSUE TITLE
FAILURE_PREPARE_WORKSPACE is shown as "Preparation finished"

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capella-collab-manager#1724]
When a pod fails to start up and prints out `---FAILURE_PREPARE_WORKSPACE---`, the Collab Manager shows "Preparation finished" on the "Sessions" page. This is misleading, as "finished" usually means that the session will become available within a few seconds. Instead, it should clearly show that an error occurred, and starting the session will be retried after a short time.

**Comment by MoritzWeber0** [comment]
The session status reliability is far from optimal since we've introduced our own session preparation stage, which is not considered properly. Will be solved once this issue is implemented: https://github.com/DSD-DBS/capella-collab-manager/issues/1578

**Comment by MoritzWeber0** [comment]
Closed as completed with #1971
