### ISSUE TITLE
Move from material icons to material symbols

### ISSUE THREAD

**Issue by zusorio** [DSD-DBS/capella-collab-manager#1744]
Google's old material icon set is called "Material icons". It's deprecated and no longer gets new icons. The replacement for it is called "Material Symbols". As described in the [Angular Material docs](https://fonts.google.com/icons), we should move to the new icon set.

**Comment by MoritzWeber0** [comment]
There seems to be an issue in Angular Material as well: https://github.com/angular/components/issues/24845

We'd need to replace the `woff2` file and add the fontSet attribute to each mat-icon: `<mat-icon fontSet="material-symbols-outlined"></mat-icon>`. Not sure what the Angular Material plans are to migrate.

**Comment by MoritzWeber0** [comment]
Here is also described how to use the class per default on all mat-icons: https://material.angular.io/components/icon/overview#font-icons-with-ligatures
