### ISSUE TITLE
Export Diagram as Image fails

### ISSUE THREAD

**Issue by MartinLindenmaierSBB** [DSD-DBS/capella-collab-manager#177]
The export of a diagram fails with the following error message:

![image](https://user-images.githubusercontent.com/63055539/184605817-48d76186-17c8-4105-8ce8-d2d186c44ec2.png)

**Comment by MoritzWeber0** [comment]
This looks like a bug in Capella itself. Do you know a workaround @vik378?

**Comment by vik378** [comment]
@MartinLindenmaierSBB , it is a Capella issue indeed but you can go around it by setting the scale slider in the export dialog to "max" - then it seem to work. The next challenge is to get it out of the session container (as there is no download button). We have a feature that we'd like to publish soon that provides all diagrams as svg files + a nice index but it is a few weeks away.  May be we can make the download button available for a session container sometimes this week, @MoritzWeber0 ?

**Comment by MoritzWeber0** [comment]
Download of files is already tracked by #48. Unfortunately, I can't give a specific ETA, but I'm optimistic that we manage it in the next weeks. I'll close this issue unless there are more questions.
