### ISSUE TITLE
Feature Request: Add nodeSelector option for sessions

### ISSUE THREAD

**Issue by oanaanastasia12** [DSD-DBS/capella-collab-manager#1815]
Due to cost monitoring requests we need to ensure the scheduling of session pods is done on nodes having a specific label and currently session pods can be scheduled on any Kubernetes cluster node.

Please introduce the possibility to specify nodeSelector labels for the session pods.

**Comment by MoritzWeber0** [comment]
Resolved with https://github.com/DSD-DBS/capella-collab-manager/pull/1863
