### ISSUE TITLE
Store Feedback in Database

### ISSUE THREAD

**Issue by zusorio** [DSD-DBS/capella-collab-manager#1835]

**Comment by MoritzWeber0** [comment]
When we store it in the database, we can also drop the requirement for having a valid SMTP setup.

**Comment by MoritzWeber0** [comment]
Alternative it to expose it via the metrics endpoint and show it in Grafana. We could build nice dashboards out of it.

**Comment by MoritzWeber0** [comment]
Resolved with https://github.com/DSD-DBS/capella-collab-manager/pull/1858
