### ISSUE TITLE
Clean persistent Capella workspaces

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#191]
Sometimes weird things happen with Capella workspaces - users should be able to clear or repair their workspaces with a button in the frontend.

**Comment by MoritzWeber0** [comment]
When cleaning the workspace, there should be a confirmation popup. It should state that it deleted all models in the workspace and that they are not recoverable.

**Comment by MoritzWeber0** [comment]
The workbench state is stored in this file: `./.plugins/org.eclipse.e4.workbench/workbench.xmi`
Then, there is `./.plugins/org.eclipse.ltk.core.refactoring/.refactorings/.workspace`, which contains a history of actions in the workspace. We should also try deleting it. 
`./.plugins/org.eclipse.core.resources/.projects` contains a directory for each element.
`./.plugins/org.eclipse.core.resources/.root/3.tree` Is a binary file with tree content.

As a first approach, we should try deleting all plugins except `org.eclipse.core.resources` and `org.eclipse.e4.workbench`.

**Comment by MoritzWeber0** [comment]
Broken semantic browser: 
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/3374c3e1-d630-4c20-859d-2de30c80bfff)

Code origin may be somewhere here: 
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/35964ab1-dbca-4b45-aaee-ef26f47e326c)
https://github.com/eclipse/capella/blob/f9bdcb9647664cfb782c3f629e66073c9e2b8c66/core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java#L844

**Comment by MoritzWeber0** [comment]
A PVMT issue was reported: 
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/85d939aa-7a4f-474d-8ef9-6dcb271a6f93)

**Comment by amolenaar** [comment]
Clearing a workspace would be the same as removing the persistent volume for that that user, right?

**Comment by MoritzWeber0** [comment]
> Clearing a workspace would be the same as removing the persistent volume for that that user, right?

There are a few options: 
- Delete the whole PVC. This will remove everything from the workspace, also the projects / models and can lead to a data loss. We have to properly warn during the deletion.
- Delete only the metadata directory in the workspace. This is a bit more complicated because we need to spawn a Pod for it.
- Delete only the files which break a workspace. This will need more investigation which files are causing the workspace issues.
