### ISSUE TITLE
Can Capella work with postgresql v16?

### ISSUE THREAD

**Issue by formorter** [DSD-DBS/capella-collab-manager#1921]
Hi there. I have a question about the required postgresql version
I want to upgrade my cluster from version 15 to 16, do I have any problems with the capella functionality after update?
btw i didnt find anything about required version of postgre in documentation

**Comment by MoritzWeber0** [comment]
Hi @formorter,

In our development environment we use the latest version of postgres (`Debian 17.0-1.pgdg120+1`). 
There are no specific requirements to PostgreSQL other than it should be PostgreSQL 14 or above.
I don't expect any issues after the update from 15 to 16.
