### ISSUE TITLE
Adding custom badges to capella projects

### ISSUE THREAD

**Issue by formorter** [DSD-DBS/capella-collab-manager#1962]
Hello!
I have a question about badges, created by capellambse
We have a custom badge, that generate metadata about testing
Can i add a custom badge to my capella project?
I wana viewing badge generated by capellambse and badge generated by myself

**Comment by MoritzWeber0** [comment]
Hey @formorter,

that's not possible as of now. I turned the request into a feature request to support arbitrary artifacts / images on the model card. I can't give an ETA though.
