### ISSUE TITLE
Error when implementing hyperlinks in description editor

### ISSUE THREAD

**Issue by SergioGuindasGarciaDB** [DSD-DBS/capella-collab-manager#200]
![image](https://user-images.githubusercontent.com/85236263/186925363-096bb3e4-b116-4baa-9b54-85f200bb5627.png)

The error message above is shown quite often (but not always) when adding an hyperlink in the description editor

**Comment by vik378** [comment]
Hi @SergioGuindasGarciaDB , thanks for reporting that issue. My feeling is this is an issue with Capella on Linux itself and is worth reporting at https://github.com/eclipse/capella/issues
