### ISSUE TITLE
Link models with Git repositories

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#222]
Models of a Capella Collaboration project should be assignable to a exiting git repository. The global Git instance setting has to be used. 
The instance baseURL should be expandable with a specific path in the instance. We should prevent Path Traversal Attacks. 

![image](https://user-images.githubusercontent.com/23395732/189341046-8ee94c46-5f77-49c5-8b24-b929b2a6deeb.png)

**Comment by dominik003** [comment]
Added in #311
