### ISSUE TITLE
Verify project role before executing the backend logic

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#247]
This issue evolved from a PR discussion: https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r969768358

In the `route` modules, the `verify_project_role` should always be executed before other calls. Otherwise, users can see conflicts and gather more information with the error messages.

The conversation copied over: 
@[MoritzWeber0](https://github.com/MoritzWeber0) MoritzWeber0 [2 days ago](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r969768358)
It makes sense to check the permissions before executing other database queries like checking for project existence (just in case of DDoS attacks, etc.). Applies also to the patch route.

@[TimoBbz](https://github.com/TimoBbz) TimoBbz [yesterday](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r970794687) • 
But we don’t know the project name before doing such a request, this implies that we need to change the verify_project_role function to take the slug as argument

@[TimoBbz](https://github.com/TimoBbz) TimoBbz [yesterday](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r970805083)
Also, I’m aware that there is anyway a problem in the fact that a 404 error is raised before a 403 and that it could be used by an attacker, but same, it would need to rework the verify_project_role function

@[MoritzWeber0](https://github.com/MoritzWeber0) MoritzWeber0 [18 hours ago](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r971251012)
Indeed, the verify_project_role has to be reworked slightly. Instead of the repository parameter (which was the unique identifier of a project before), you can pass the slug (which is the new identifier). But you have to make sure that every occurrence is updated. I started the process here: https://github.com/DSD-DBS/capella-collab-manager/pull/229, but it's not finished yet - therefore it would be nice to see the change as part of this PR.

@[TimoBbz](https://github.com/TimoBbz) TimoBbz [6 hours ago](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r971681239)
I really think that this should be a PR on its own, I have 4 other PR that wait for this one, and it’s also already pretty big and overflows its scope by a lot. And also because it would be easier to change all it’s occurrences if it’s in one PR.

@[TimoBbz](https://github.com/TimoBbz) TimoBbz [6 hours ago](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r971706786)
And also, I think it could be solved way more elegantly. The solution would be to introduce a FastAPI injectable User object (not yet sure of the name), whose constructor returns a User or raises a 403.

**Comment by MoritzWeber0** [comment]
> @[TimoBbz](https://github.com/TimoBbz) TimoBbz [6 hours ago](https://github.com/DSD-DBS/capella-collab-manager/pull/189#discussion_r971706786) And also, I think it could be solved way more elegantly. The solution would be to introduce a FastAPI injectable User object (not yet sure of the name), whose constructor returns a User or raises a 403.

This is a nice solution indeed. I always thought that there is no way to pass the URI parameters to the dependency injection, but this is possible.

**Comment by MoritzWeber0** [comment]
More information can be found here: https://fastapi.tiangolo.com/tutorial/dependencies/

**Comment by TimoBbz** [comment]
The goal I though about for this dependency injection was to filter out unauthenticated users, not to check that they have rights on the project. But perhaps is it possible to access the URI params in the injected function.

**Comment by MoritzWeber0** [comment]
In my experience with the project, authentication handling is sometimes a bit unclear - you have to check to body to check which endpoints has which restrictions. Having it in one specific place (with an injectable that can have some advanced validations) should lead to a clearer structure (and more security, because developers can directly see the protection of a route).
