### ISSUE TITLE
Change `projects_name` to `project_slug`

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#319]
We should consistently change `projects_name` to `project_name` as you did for `get_user_of_project`. But this can also be done from my side when I revise the uses of the project name.

_Originally posted by @dominik003 in https://github.com/DSD-DBS/capella-collab-manager/pull/312#discussion_r997191158_
      

Additionally, we should change the `project_name` to `project_slug` where applicable.

**Comment by MoritzWeber0** [comment]
When we reference the database, we should always use the project ID. Reason: The slug should be changeable: https://github.com/DSD-DBS/capella-collab-manager/issues/396

**Comment by TimoBbz** [comment]
Related PR: https://github.com/DSD-DBS/capella-collab-manager/pull/423
