### ISSUE TITLE
Jupyter integration

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#39]
Integrate Jupyter or JupyterHub. 

In the project overview, a user should be able to spawn a Juypter notebook with the model preloaded. There should exist some example scripts. `py-capellambse` is preinstalled (https://github.com/DSD-DBS/py-capellambse). 

Persistent volumes should exist on different levels: Global mounts (read/only for users, write for administrators), project mounts (a folder per project, read-only for read-only project users, read/write for read/write project users) and a personal mount (where you can just do whatever you want). 

A user should be able to spawn the Jupyter notebook from the Collab Manager (like the sessions). It may be worth investigating if JupyterHub is a good option.

**Comment by amolenaar** [comment]
Example: https://colab.research.google.com/

Which direction to go:

1. One session
2. One session per project
3. Personal workspaces

How to provide models to the jupyter containers? How to expose containers?

**Comment by MoritzWeber0** [comment]
> Example: https://colab.research.google.com/

This is good example indeed.

> Which direction to go:
> 
> 1. One session
> 2. One session per project
> 3. Personal workspaces

It depends on the implementation effort. In general, it is important that users can only see models from projects where the user has access to. In addition, we need to allow collaboration within projects. 

We have differentiate between sessions and workspaces. For clarification, I'd call one Docker container a session and a volume or file share a workspace.

We need at least two workspaces for the beginning: 
- A personal workspace
- A project workspace
In the future, we may need a global templates store, which can only be edited by administrators. For more details, see the description of this issue. 

Which type of session we'd like to use depends on the type of Jupyter. If we use JupyterLab, one container is probably enough. If we use JuypterHub, we would need to have one session per user or one session per project. 

> How to provide models to the jupyter containers? How to expose containers?

Models can be cloned from the corresponding Git repository during startup. Containers can be exposed via one nginx container, which has an Ingress endpoint. The nginx container redirects to the Jupyter container internally. The jupyter containers are exposed via ClusterIP/DNS.

**Comment by amolenaar** [comment]
From what I see, the functionality of JupyterHub overlaps a lot with what we already do in Collab Manager: manage users and sessions. It would be interesting to see how they keep track of the sessions and make users access their own session.

JupyterHub only provides per-user workspaces.
