### ISSUE TITLE
provide means to rename a project

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#396]
In the current UI we are missing a feature that would enable project name change. As projects were migrated from the earlier instance, they inherited names of the models which might be misleading in some cases

**Comment by MoritzWeber0** [comment]
Renaming projects is an easy one.
Renaming the slug is a bit more difficult, because it used for URLs and in some parts of the code. 
For the URL: Do we need a redirect or can we just change the route then?
For the code: These need to be refactored to use the project ID instead.

**Comment by TimoBbz** [comment]
Proposal:
- A project renaming doesn’t change the slug. The priority is the persistence of the link imo.
- Allow projects with name inducing the same slug, and implement a behavior to prevent duplicate slugs. Ex, if the project _Test_ (slug: `test`) exists, the project _tesT_ could be created, and the autogenerated slug would be `test-1`, then `test-2`, etc.

**Comment by TimoBbz** [comment]
Related PR: https://github.com/DSD-DBS/capella-collab-manager/pull/424
