### ISSUE TITLE
Provide means to archive a project

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#397]
There are quite a few projects that aren't developed anymore - but read-only access would still be of interest. For those it would be nice to indicate that the project is "frozen" by maybe graying-out the project card and adding an archived tag somewhere on the project page.

**Comment by MoritzWeber0** [comment]
Filtering it out from the projects list would be nice. The TeamForCapella repositories should not be injected in persistent sessions.
