### ISSUE TITLE
Access control and auditing

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#398]
We need means to audit user access history. "manage users" perspective seems to be the right place for it.

What we should see there for an individual user is:

* when the user got access to the system
* last login date and time
* what projects and models the user has access to at the moment
* complete access rights history that shall include entries like:
   * <date time>: User <name> was granted <access level> to the <project / model> by <access sponsor>; reason for authorization: <free text that explains why the user shall have access to the project and that specific level of access>
   * <data time>: User <name> access authorization was revoked by <user who revoked authorization> due to <reason>

**Comment by MoritzWeber0** [comment]
Is it sufficient to store these events in the logs? Then, it is already covered by #353. 
If it is beneficial to have UI elements for it, we can consider it of cause.
