### ISSUE TITLE
Introduce Project perspective

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#40]
The platform needs to be project focused, as in - the first thing that a user should see is the list of projects that the user is invited to work on or means to create a new project if the user is allowed to (only admin role can create new project):

![image](https://user-images.githubusercontent.com/8280844/158978934-1035fa86-183b-4df4-aa0f-3aa9f604c3e4.png)

The project may look similar to the below screenshot:

![image](https://user-images.githubusercontent.com/8280844/158985091-587b4189-e517-40e3-a57f-45d9af36a827.png)

Project configuration view should enable CRUD for a model entry. Model entry should be described by the following fields:
* name
* description
* nature (library or project)
* derived editing nature (default is Git, T4C if T4C project and repo is linked)

 Model configuration view should enable the following:
* link/unlink T4C repository and project
* add git repo (and set repo as primary)
* if T4C is set -> configure sync from T4C to git (when, how, credentials)

**Comment by MoritzWeber0** [comment]
Current state, the following steps are missing: 

- [ ] Make request session working
- [ ] Create projects doesn't work for users without admin rights
- [ ] Manage models (backups, linked sources)
- [ ] Mange Dockerimages in settings (as Tools setting)
- [ ] Add spinner for Git modelsource (settings)
- [ ] Team4Capella model source integration 
- [ ] Guacamole credentials in database

**Comment by MoritzWeber0** [comment]
Since this issue includes a complete new version, the issues will be tracked in smaller variants in the future. You can filter for the related issues with the label "version:v2": https://github.com/DSD-DBS/capella-collab-manager/labels/version%3Av2
