### ISSUE TITLE
Add "albumentations" ERROR

### ISSUE THREAD

**Issue by Cfisher-T** [DSD-DBS/capella-collab-manager#605]
In Jupyter Notebook add "albumentations",i have error.I try to `pip install numpy==1.16.1or others` but error still!
I can add it in PyCharm, but jupyter notebook can't add.
I don't know how to solve it!  
I hope someone could help me ,thanks!
![image](https://user-images.githubusercontent.com/77875921/218292088-f2d2083f-17c6-43f9-9c8e-58a422b06ead.png)

**Comment by MoritzWeber0** [comment]
Hi, we don't provide any Jupyter notebooks. In general, this issue doesn't seem to be related to this repository.
