### ISSUE TITLE
Display Timeout and Automatic Save All at Termination of Capella Session

### ISSUE THREAD

**Issue by MS34449** [DSD-DBS/capella-collab-manager#621]
Hi,

besides the Guacamole timeout which would not terminate Capella (container) there is also a inactivity timeout that terminates it, therefore: 

1. As a user of Capella in a collab-manager session I want to see the time left to termination because of inactivity to be able to react e.g. by performing some action in the Capella GUI.

 When the Capella is closed because a persistent session is terminated due to inactivity or manually via the button in the collab-manager, currently all unsaved changes are lost. Thus:

2. As a modeller I want all changes in all open models to be saved automatically when terminating the session due to inactivity or by clicking Terminate or at least have the possibility to set this behaviour in the configuration in order not to loose any changes I have made in the models.

br
Marek

**Comment by MoritzWeber0** [comment]
For a better overview, I've moved this issue into two separate issues: 
- The first part ("Display time until session will be terminated") is managed here: https://github.com/DSD-DBS/capella-collab-manager/issues/1486
- The second part ("Automatic saving of Capella models") will be tracked in another repository, which is currently internal. When the repository is published, it will appear in this issue.
