### ISSUE TITLE
Skeleton loader for projects is broken

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#643]
The skeleton elements start in the second row, but they should start in the first row. Also, the number of projects in not calculated properly anymore.
![image](https://user-images.githubusercontent.com/23395732/221127735-bf703cdf-74f4-4dcf-a3b0-c4cf6f750353.png)

**Comment by dominik003** [comment]
Apparently the problem has been fixed in the meantime, so nothing todo here.
