### ISSUE TITLE
Disable download button for diagrams where diagram-cache export failed

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-collab-manager#656]
Instead of pressing the button and receiving the red `error occured` info box it should be better to disable/grey-out the download button. This indicates that the diagram-cache export job failed for this diagram.

**Comment by Wuestengecko** [comment]
> disable/grey-out the download button

There should also be a more explicit indicator to the user as to why it's disabled, which could be e.g. a little popup on mouse-over of the button (Something along the lines of "Download unavailable: Export has failed").
