### ISSUE TITLE
Authentication failed while logging on https://capella.ertms.be/

### ISSUE THREAD

**Issue by PLeMag** [DSD-DBS/capella-collab-manager#703]
Hie,

I try to log on the above server. 
I have access to:
Image has been removed.

I get to this point:
Image has been removed.

I copy my 'T4CLogin password'.

Before I get to use it, I get following error message:
Image has been removed.

I get this error for both Capella 5.2.0 and 6.0.0.
Prior to this, I used to be asked for my authentication.
What am doing wrong ?

**Comment by MoritzWeber0** [comment]
Hi @PLeMag, thanks for the request. Please don't expose internal information in our Github project board. Please write an email to set@deutschebahn.com, so that we can investigate your authentication issue. Thanks!
