### ISSUE TITLE
Add support for internal projects

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#713]
It should be possible to have internal projects. Internal projects are visible for all users, which are logged in. Users without explicit project access should have the same access permissions like `read-only` users in "internal" projects.

**Comment by amolenaar** [comment]
I suppose we can have two levels, similar to what GitLab is using:

* Internal - everybody with an account can see the model, and run it in a read-only session
* Public - you do not need an account, but you can only see the rendered diagrams and are not allowed to start a session.

For starters we're probably after the "internal" version, where logged in users can view the model.

**Comment by Paula-Kli** [comment]
I think for public projects we want to have the same access as the read-only users have - you have to be logged into the collab manager but do not need to have rights on the github repo

**Comment by MoritzWeber0** [comment]
> I suppose we can have two levels, similar to what GitLab is using:
> 
> * Internal - everybody with an account can see the model, and run it in a read-only session
> * Public - you do not need an account, but you can only see the rendered diagrams and are not allowed to start a session.
> 
> For starters we're probably after the "internal" version, where logged in users can view the model.

I was looking after `internal` projects in the issue. Public projects are also interesting, I've opened a separate issue for it: https://github.com/DSD-DBS/capella-collab-manager/issues/836

**Comment by amolenaar** [comment]
Since we have a different issue for public projects, we can close this issue.
