### ISSUE TITLE
Add Python CLI interface with helpful scripts

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#743]
For the start, a script which copies the workspace of a user to a local directory:

Interface: 
`python -m capellacollab.cli.workspace --kube-context <context> --namespace <namespace> --username <username> --output <output-dir>`

It should create a Pod with the PVC mounted (as context manager), the run `kubectl cp` and remove the Pod again.

**Comment by MoritzWeber0** [comment]
We also need an upload feature to upload complete workspaces.

**Comment by dominik003** [comment]
Resolved by https://github.com/DSD-DBS/capella-collab-manager/pull/1039
