### ISSUE TITLE
Workspace state: unknown

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#75]
We should be able to indicate container state at all times, also it would be great if we could indicate to the users how long the container is running - like "Running for last 2 seconds / 30h / days / years"

<img width="327" alt="image" src="https://user-images.githubusercontent.com/8280844/166653805-89d2f2ec-f6af-4fed-a4ed-97122648210f.png">

**Comment by MoritzWeber0** [comment]
I will have time in about two weeks to fix this issue.

**Comment by MartinLindenmaierSBB** [comment]
Hi @MoritzWeber0, any plan, when this issue will be fixed?

**Comment by MoritzWeber0** [comment]
> Hi @MoritzWeber0, any plan, when this issue will be fixed?

Hi @MartinLindenmaierSBB. Unfortunately, I only see the message now. Sorry for that. We are working on version 2 of the Collaboration Manager right now, which will also include the fix for the "unknown state" issue. The release is planned in two weeks at the latest.
