### ISSUE TITLE
Expose documentation for sessions

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#753]
Session containers should be able to expose the documentation (web-based) on a specific port. The documentation should be displayed to the user (e. g., via a documentation button in the session overview).

Related to https://github.com/DSD-DBS/capella-dockerimages/issues/159

**Comment by MoritzWeber0** [comment]
I had a look into how Eclipse handles the documentation exposure: 

- When clicking on "Help" -> "Help Contents", Eclipse starts a web server on a random port. The web server is not available before. In addition, it starts a web browser default, which fails in our sessions.
- A custom web browser can be configured. I used a simple Python script as mock. The Python script can also be used to open a `tkinter` message to the user, e.g., "To see the documentation, please continue in the Capella Collaboration Manager".
- Several options are available in the Help view in Eclipse: 
   ![image](https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/d99e6f09-9583-49c0-9844-a6a1899796ab)
  It's possible to open the help in the "dynamic help view" but this opens a full-screen application which can not be closed via the UI, so it's not really an option.
- There is another button "Show contextual help". It seems to display the same help and works without further configuration. Is this sufficient for now? @vik378  

When implementing it in a way that the user can open the documentation in the same browser where the Guacamole session lives, a workflow could look like: 
1. User has to open session
2. In the session, the user has to click on Help
3. We run a python script "as web browser", sending a request to the backend with the connection information. The backend can communicate with the Collaboration Manager interface to enable a documentation button, which then opens the documentation in a new tab.

Pretty complex workflow, not sure if it's worth the effort.

**Comment by MoritzWeber0** [comment]
Duplicate of https://github.com/DSD-DBS/capella-collab-manager/issues/576

**Comment by vik378** [comment]
I'd rather "un-close" this issue since there is still no way for an end user of collab manager to get to the Capella help, lets keep it open until it is properly sorted.
