### ISSUE TITLE
Disposal of abandoned sessions

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#76]
When session is not active for more than defined timeout (configurable), the allocated compute resource should be disposed. We could consider complete disposal or hybernation, however we need to see what is the effect on license use in case of sessions with TeamForCapella projects

**Comment by MoritzWeber0** [comment]
We need a periodic task runner for it. In theory, also kubernetes CronJobs can be used, but it's missing some flexibility. 

In my opinion, Celery looks really promising and should be easy to integrate: 
https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html
