### ISSUE TITLE
Drop `target` in `values.yaml`, replace it with `development`

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#770]
People started using the Capella Collaboration Manager with target `local` on local servers. However, it's not a development server, it's used for "production". The name local is therefore not clear enough.

The goal is to drop target and just have boolean value for the development mode instead of a enum.

**Comment by amolenaar** [comment]
`target` current needs to have a value `local` or something else, there's no specific case for the `azure` target anymore.

`target` is still used for a couple of things:

* Sizing of containers - on a local environment memory limits are lower
* Volume mounts
  *  For backend postgres database, hosted in the cluster
  * For guacamole database
* Expose Grafana loki on development systems for direct access
* Set ingressClass to nginx on non-local setups. K3d uses Traefik
