### ISSUE TITLE
Reorder models in project

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#809]
Interactively reorder models in the model overview in the project details.
Reordering should be possible for project leads. The changes should be visible for all project members.

Gridster2 could be helpful: https://github.com/tiberiuzuld/angular-gridster2

**Comment by romeonicholas** [comment]
I have a couple concerns with using a drag and drop grid system for this:
- Not mobile-friendly for elements of this size
- Re-ordering on every drop is a lot of database writes
- This would be the first use of this interaction paradigm, meaning we should consider where else we would want to add it so we choose the right system and design from the start

If we aren't expecting users to do this constantly, a lighter-weight implementation to gauge how often project leads want to do this might be a "Reorder models" button that pops up a modal with a simpler vertical reorderable list form (e.g. https://material.angular.io/cdk/drag-drop/examples). 

Any specific requirements on this issue @MoritzWeber0?

**Comment by MoritzWeber0** [comment]
> I have a couple concerns with using a drag and drop grid system for this:
> 
> * Not mobile-friendly for elements of this size

This is right, even though I saw drag and drop on mobile. A simple vertical list with drag&drop as mentioned below should be usable on mobile devices too.

> * Re-ordering on every drop is a lot of database writes

We have so few transactions that we do not have or will have any capacity problems with the database.

> * This would be the first use of this interaction paradigm, meaning we should consider where else we would want to add it so we choose the right system and design from the start

I don't think that reordering in that sense will be used anywhere else. We want to have custom order of projects at some point, but these will be ordered according to specific criteria (favorites, number of models, number of project users, etc.). 

> If we aren't expecting users to do this constantly, a lighter-weight implementation to gauge how often project leads want to do this might be a "Reorder models" button that pops up a modal with a simpler vertical reorderable list form (e.g. https://material.angular.io/cdk/drag-drop/examples).

This sounds like a easy and intuitive solution for me.

> Any specific requirements on this issue @MoritzWeber0?

No, I don't have any concrete thoughts about it. A separate button to reorder models with a vertical drag&drop list is fine for me.
