### ISSUE TITLE
Permanent "session crashed unexpectedly" when starting persistent Capella 6.0. sessions

### ISSUE THREAD

**Issue by MS34449** [DSD-DBS/capella-collab-manager#810]
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/82209355/7b14fca5-c793-42c7-b999-0f961b53d90b)

**Comment by MS34449** [comment]
Now it works again. Leaving the issue open so ithe root cause could be investigated.

**Comment by MoritzWeber0** [comment]
Hi, as this refers to one of our internal instances, please create a ticket in our service desk to investigate further.

**Comment by MS34449** [comment]
Hi, this ticket has been created using the button "Open issue on Github" in collabmgr., which is obviously the most convenient way  and actually it should be the right one, even for an "internal instance" - may be ithe button could be redirected to an internal instance or disabled instead of each time asking to duplicate the ticket. If that would be difficult, you can still clone this ticket yourself to a service desk ticket, don´t you?

**Comment by MoritzWeber0** [comment]
Hi @MS34449,

I'm currently unable to reproduce the issue. Also, it's hard to debug it after session closure. The next time you encounter the issue, please send me a message on Teams and keep the "broken" session open. I can then look into it. Most of the time, "Session crashed unexpectedly" refers to the downtime of another system on which we depend. 

Github is intended for general issues in the code of the Capella Collaboration Manager. As Github is public, I'm unable to provide any internal information, which is needed in this case to give a proper reply.

I'll send you a reply privately with more information.
