### ISSUE TITLE
Backend development w/o frontend: How to authenticate?

### ISSUE THREAD

**Issue by jamilraichouni** [DSD-DBS/capella-collab-manager#82]
Hi!

When running the backend in development mode as described in the `​CONTRIBUTING.md​`.
How does one authenticate when executing requests

- via the Swagger UI (e. g. `http://127.0.0.1:8000/docs#/Sessions/get_current_sessions_api_v1_sessions__get`),
- test requests using the ​`requests​` module (e. g. `requests.get(url="http://127.0.0.1:8000/api/v1/sessions")`), and/ or
- using `​curl`​?

I tried ​`http://127.0.0.1:8000/api/v1/authentication​` and received an `​auth_url` .
Visiting that URL I get the ​Mock OAuth2 Server Sign-in​ page with a redirect to the Angular frontend.

I'm not running the frontend. Today, I'm a backend developer/ tester.

A little example will help.
I can then document how one authenticates and afterwards sends requests to the backend w/o any frontend.

Thanks!
Jamil

**Comment by MoritzWeber0** [comment]
Hi, the flow follows the OAuth specification (https://datatracker.ietf.org/doc/html/rfc6749).
After authenticating against the `auth_url`, you should be able to request an access_token (on the corresponding endpoint) with the `code` and `state` parameters from the redirect uri.
Please provide the access_token in the `Bearer` header.

**Comment by jamilraichouni** [comment]
See commit da19447ebc60a1a836d9b40220c2e6707673b9a5.
Issue can be closed when `staging` is being merged onto `master`.
