### ISSUE TITLE
Capella freezes during pull requests, especially e.g. after the pull request has resulted in "no new versions to pull"

### ISSUE THREAD

**Issue by MS34449** [DSD-DBS/capella-collab-manager#821]
... eg. toay around 16:05. This issue has been reported also by other team members.

**Comment by vik378** [comment]
@MS34449 , any chance you can update the issue title and description so that it makes sense to a wider audience?
Ideally with some screenshots and instructions for how to reproduce that failure. We cant help otherwise. Thanks.

**Comment by MS34449** [comment]
Hi, actually, there is not much more information I can add. The title says it all - when a pull request is started and tehre is nothing to pull, then Capella freezes. The pull request is tarted via context menu in the Git repositories tab, though I assume the same happens regardless by what means it is dtarted within Capella GUI. After entering the user name and pw, Capella displays the usual pull result page, which in this case says just "nothing to fetch" and it freezes (no reaction to user input). In case this page is unfamiliar to you, I have attached a screenshot. It seems to be reproducible.
![Capella_freeze_nothing_to_pull_2023-07-04 14_50_26-Window](https://github.com/DSD-DBS/capella-collab-manager/assets/82209355/dc471a27-d257-4a5e-8af0-6fdfae653be5)

**Comment by MoritzWeber0** [comment]
Hi @MS34449,

thanks for opening the bug report. After looking into the logs, I can not see any suspicious entry. 
Can you open the "Error log" view in Capella and check for any error messages at the time where the bug occured? If the bug occurs again, it would be great if you can comment on this PR (alternatively via the service desk or privately via Teams). We could select the logs at the particular timestamps then to see if there is any suspicious activity. 

You mentioned that the issue can be reproduced by your team members. Can you provide me the names of the affected team members privately? 

Thanks in advance.

**Comment by MoritzWeber0** [comment]
The result of a private conversation with @MS34449 was that he saved the password in the Eclipse secure storage. When not using the Eclipse secure storage, it doesn't freeze anymore.
