### ISSUE TITLE
Add a button for instructions on how to add a jupyter notebook from the SessionViewer to the plugin store

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-collab-manager#879]
When a user has developed a nice routine in a Jupyter notebook and she wants to reuse and execute this regurlary the best way should be to make a Plugin out of it. So having a button `How to add this notebook as a plugin` which opens a dialog with steps on how to create a mbse works plugin with this routine would be cool.

**Comment by MoritzWeber0** [comment]
Since we're far away from having a plugin store at all, I'll close this issue to keep the list of issues clean. The current implementation status is tracked in this PR: https://github.com/DSD-DBS/capella-collab-manager/pull/722
