### ISSUE TITLE
Consider custom exceptions in OpenAPI documentation

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#883]
Custom exception handlers should also appear as possible responses in the auto-generated OpenAPI specification.

**Comment by romeonicholas** [comment]
Rought idea, but what do you think of this @MoritzWeber0? 

- basic error pydantic models
- a function to create error responses
- generating responses just above each route so they can then be used in the responses list (this is what makes them appear in OpenAPI)

The things I'm still trying to figure out:
- This lets every error have its own example in the documentation, though then we're documenting in the route instead of in the pydantic model
- Do we have any routes that have multiple ways to reach the same error status code? This might not allow us to document multiple reasons for a specific error code without resorting to something silly like a long string with a separator, but I haven't tested it/checked
- We could pass both technical and user descriptions this way, but not sure if that's necessary or helpful

I just tested this out on the user routes for users/id:

users/user_id:
<img width="917" alt="user_id" src="https://github.com/DSD-DBS/capella-collab-manager/assets/79602065/71718b71-eda1-4de7-8a2d-6b7015b8b139">

```
class ErrorDetail(pydantic.BaseModel):
    err_code: str
    reason: str

class ErrorResponse(pydantic.BaseModel):
    status_code: int
    detail: ErrorDetail

def create_error_response(
    status_code: int, err_code: str, reason: str
) -> dict:
    return {
        "model": ErrorResponse,
        "description": "Maybe a technical description as opposed to the user one?",
        "content": {
            "application/json": {
                "example": ErrorResponse(
                    status_code=status_code,
                    detail=ErrorDetail(
                        err_code=err_code,
                        reason=reason,
                    ),
                ).model_dump()
            }
        },
    }

NO_PROJECTS_IN_COMMON_RESPONSE = create_error_response(
    status_code=status.HTTP_403_FORBIDDEN,
    err_code="NO_PROJECTS_IN_COMMON",
    reason="You need at least one project in common to access the user profile of another user.",
)

@router.get(
    "/{user_id}",
    response_model=models.User,
    responses={status.HTTP_403_FORBIDDEN: NO_PROJECTS_IN_COMMON_RESPONSE},
)
def get_user(
    own_user: models.DatabaseUser = fastapi.Depends(injectables.get_own_user),
    user: models.DatabaseUser = fastapi.Depends(injectables.get_existing_user),
    db: orm.Session = fastapi.Depends(database.get_db),
) -> models.DatabaseUser:
    if (
        user.id == own_user.id
        or len(projects_crud.get_common_projects_for_users(db, own_user, user))
        > 0
        or auth_injectables.RoleVerification(
            required_role=models.Role.ADMIN, verify=False
        )(own_user.name, db)
    ):
        return user
    else:
        raise fastapi.HTTPException(status_code=status.HTTP_403_FORBIDDEN)
```

**Comment by romeonicholas** [comment]
Ugh, just realized raising the exception that way would break the existing error interceptor. So it seems like it would be a even more duplication, because you'd need to repeat everything for both the responses and for raising the exception itself? Seems like there must be a way to avoid that

**Comment by MoritzWeber0** [comment]
> Rough idea, but what do you think of this @MoritzWeber0?
> 
> * basic error pydantic models

We don't use pydantic models as of now and I want to avoid that we have to define exceptions twice. Have look at the exception files, e.g. `capellacollab/users/exceptions.py`. We already define the exceptions here, it would be great if we could use them.
> * generating responses just above each route so they can then be used in the responses list (this is what makes them appear in OpenAPI)
It would be nice if we could easily register all exceptions a API route can throw, e.g. via an annotation. 
Better would be if it's completely auto-determined by scanning the AST of the function to detect which exceptions a function can raise: https://stackoverflow.com/questions/32560116/how-to-list-all-exceptions-a-function-could-raise-in-python-3

> The things I'm still trying to figure out:
> 
> * This lets every error have its own example in the documentation, though then we're documenting in the route instead of in the pydantic model
> * Do we have any routes that have multiple ways to reach the same error status code? This might not allow us to document multiple reasons for a specific error code without resorting to something silly like a long string with a separator, but I haven't tested it/checked
Don't have an example right now, but this case should exist somewhere. That's why we often use the exceptions files to define exceptions which can then be used in different places. 
> * We could pass both technical and user descriptions this way, but not sure if that's necessary or helpful
Would leave it out for now.
> I just tested this out on the user routes for users/id: <img alt="user_id" width="918" src="https://private-user-images.githubusercontent.com/79602065/306309489-18e0f561-c0b5-4111-9a0d-4698404ffd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDQxMzYsIm5iZiI6MTcwODUwMzgzNiwicGF0aCI6Ii83OTYwMjA2NS8zMDYzMDk0ODktMThlMGY1NjEtYzBiNS00MTExLTlhMGQtNDY5ODQwNGZmZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA4MjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDRiNGMzNTYyNTZhYmIxOTg3ZWY5MzdiMGYxMWY3OTA4MDEyMThlYmJjMjFjNDMwYjYzZjI0OWNkY2IwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6oo-UdwWFz8vROxKDKqQBMYBFFGmoebx1WTaDOqoRI">

Looks good.

> ```
> class ErrorDetail(pydantic.BaseModel):
>     err_code: str
>     reason: str
> 
> class ErrorResponse(pydantic.BaseModel):
>     status_code: int
>     detail: ErrorDetail
> 
> def create_error_response_and_exception(
>     status_code: int, err_code: str, reason: str
> ) -> dict:
>     return {
>         "response": {
>             "model": ErrorResponse,
>             "description": "Maybe a technical description as opposed to the user one?",
>             "content": {
>                 "application/json": {
>                     "example": ErrorResponse(
>                         status_code=status_code,
>                         detail=ErrorDetail(
>                             err_code=err_code,
>                             reason=reason,
>                         ),
>                     ).model_dump()
>                 }
>             },
>         },
>         "exception": {
>             "status_code": status_code,
>             "detail": {
>                 "err_code": err_code,
>                 "reason": reason,
>             },
>         },
>     }
> 
> NO_PROJECTS_IN_COMMON = create_error_response_and_exception(
>     status_code=status.HTTP_403_FORBIDDEN,
>     err_code="NO_PROJECTS_IN_COMMON",
>     reason="You need at least one project in common to access the user profile of another user.",
> )
> 
> @router.get(
>     "/{user_id}",
>     response_model=models.User,
>     responses={status.HTTP_403_FORBIDDEN: NO_PROJECTS_IN_COMMON["response"]},
> )
> def get_user(
>     own_user: models.DatabaseUser = fastapi.Depends(injectables.get_own_user),
>     user: models.DatabaseUser = fastapi.Depends(injectables.get_existing_user),
>     db: orm.Session = fastapi.Depends(database.get_db),
> ) -> models.DatabaseUser:
>     if (
>         user.id == own_user.id
>         or len(projects_crud.get_common_projects_for_users(db, own_user, user))
>         > 0
>         or auth_injectables.RoleVerification(
>             required_role=models.Role.ADMIN, verify=False
>         )(own_user.name, db)
>     ):
>         return user
>     else:
>         raise fastapi.HTTPException(**NO_PROJECTS_IN_COMMON["exception"])
> ```

In any case I'd keep the native Python way to use exceptions, to raise them. 
But what we could do is to restructure the exceptions a bit.

Let's look at the current structure (example `capellacollab/users/exceptions.py`:

```py
@dataclasses.dataclass
class UserNotFoundError(Exception):
    username: str | None = None
    user_id: int | None = None

async def user_not_found_exception_handler(
    request: fastapi.Request, exc: UserNotFoundError
) -> fastapi.Response:
    return await exception_handlers.http_exception_handler(
        request,
        fastapi.HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "title": "User not found",
                "reason": f"The user '{exc.username or exc.user_id}' doesn't exist.",
            },
        ),
    )


def register_exceptions(app: fastapi.FastAPI):
    app.add_exception_handler(
        UserNotFoundError, user_not_found_exception_handler  # type: ignore[arg-type]
    )
```

As you already can see, this is a lot of boilerplate. We could also generate the error message in the Exception directly:

```py
@dataclasses.dataclass
class UserNotFoundError(Exception):
   def __init__(self, username: str | None = None, user_id: int | None = None):
      self.status_code=status.HTTP_404_NOT_FOUND
      self.title = "User not found"
      self.reason = f"The user '{username or user_id}' doesn't exist."
```

Then, we could remove the `user_not_found_exception_handler` function. 
In addition, we can have a central registration of exceptions, for example a dictionary:

```py
registered_exceptions = {UserNotFoundError}
```

The main function could pick it up and register all registered exceptions properly.
In addition, we can add `create_error_responses([UserNotFoundError])` to the route and generate the docs from the Exception directly. What do you think about it?
