### ISSUE TITLE
Sessions can't be killed when restarting collab-manager

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-collab-manager#93]
When undeploying the collab manager app without terminating sessions the sessions remain in the t4c-sessions namespace with state running and can't be killed manually. They restart everytime.

## Proposed solution

Make deploy needs to scan if sessions are still alive, assign survived sessions to the correct user.

**Comment by MoritzWeber0** [comment]
Hi! Scanning sessions is a bit "overkill" in my view. The described behaviour happens only if the database gets cleaned, which will never happen in a production instance.  
We should rather clean the sessions workspace when running `make undeploy`.

**Comment by ewuerger** [comment]
I was also incorrect about killing sessions manually. This is easy and working by 
```bash
kubectl delete --all deployments -n t4c-sessions
```
