### ISSUE TITLE
Ignore promtail events for session status derivation

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#941]
To derive the session status, we scan the Pod events in the k8s operator. This does include the session container, but also the promtail container. Unfortunately, there is no way to filter events for a specific container. 

Promtail containers can be restarted during session runtime, which manipulates the session state. For example, when the promtail container is pulled, the session status changes to "Pulled", which is translated to "Preparation finished" in the frontend. This leads to disabled "File browser" and "Connect" buttons even though the session itself is alive and running.

We need a small script to filter out common promtail events. 

```
21m         Normal   Created          pod/tcjmdkhgnzmuhhdfakqiqhwsq-8669b6df8-qcqpl   Created container promtail
21m         Normal   Started          pod/tcjmdkhgnzmuhhdfakqiqhwsq-8669b6df8-qcqpl   Started container promtail
21m         Normal   Pulled           pod/tcjmdkhgnzmuhhdfakqiqhwsq-8669b6df8-qcqpl   Container image "<docker-registry>/grafana/promtail" already present on machine
```

We can filter for `promtail` and the image name to filter out the above mentioned events.

In addition, there should be an option in the frontend to still open the file browser or connect to a session in case the status is not derived properly. Connecting should include a warning that the session might not be alive.

**Comment by dominik003** [comment]
While investigating this issue, I figured out a way to actually detect to which container an event belongs. The event object has a field `involved_object` which by itself again has some fields. The interesting one is the `field_path` field as it can have three different values in our use case:

1. `'spec.containers{promtail}'`
2. `'spec.containers{oqvdoofszsvaomnwxwcteurjw}'`
3. `None`

Therefore, simply checking whether `promtail` is within the 'field_path` object should be sufficient.
