### ISSUE TITLE
Unable to open jupyter session in session viewer under Mozilla Firefox

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/capella-collab-manager#962]
On trying to open a Jupyter session in the session viewer Firefox users are greeted with the following error:
![Screenshot from 2023-08-23 11-33-29](https://github.com/DSD-DBS/capella-collab-manager/assets/50786483/9e2af82b-b718-4f55-a260-8a0b098b1b21)

There's no option to proceed. The problem may caused by the missing protocol specification (protocol-relative URL) in `sessions-capella.apps.dbcs-madrid.comp.db.de`. This is a show stopper for any Firefox user.

**Comment by MoritzWeber0** [comment]
Hi @ewuerger,
this is not a general issue. The error message indicates that your Firefox doesn't trust the certificate for `sessions-capella.apps.dbcs-madrid.comp.db.de`. Please import the certificate and it should just work again.
