### ISSUE TITLE
Delete TeamForCapella servers

### ISSUE THREAD

**Issue by dominik003** [DSD-DBS/capella-collab-manager#971]
Currently, it's not possible to delete TeamForCapella servers from the Collaboration Manager. Deletion should work as follows:

- Deletion of a TeamForCapella server. This should be used when a server has been accidentally. In case of the deletion, all TeamForCapella links to models should be deleted.

**Comment by amolenaar** [comment]
In some cases (e.g. when removing a model source, it works the other way around: all references should have been deleted, and only then the model source.
