### ISSUE TITLE
Read-only session user docs are outdated

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/capella-collab-manager#977]
The user docs about read-only sessions are outdated. Specifically I looked at the pages:
- sessions/request.md
- sessions/types/read-only.md (the "eye" icon is gone)

**Comment by amolenaar** [comment]
Which language to use? American English or British English? I had a bit of a read and currently we use a mixture.

**Comment by MoritzWeber0** [comment]
> Which language to use? American English or British English? I had a bit of a read and currently we use a mixture.

American English.
