### ISSUE TITLE
Implement skeleton loader in the frontend

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#98]
Implement skeleton loader in the frontend: https://github.com/willmendesneto/ngx-skeleton-loader

**Comment by MoritzWeber0** [comment]
Skeleton loader could also be nice: https://github.com/willmendesneto/ngx-skeleton-loader

**Comment by dominik003** [comment]
Resolved by #302 and several other follow up PRs introducing different types of skeleton loaders
