### ISSUE TITLE
Prioritize Pod error status over `START_PREPARE_WORKSPACE`

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#980]
Our Jupyter image in capella-dockerimages has no error handling and never raises `FAILURE_PREPARE_WORKSPACE` in the logs. Therefore, the sessions hangs in the status `Session preparation` until session termination. It should display an error message instead.

**Comment by dominik003** [comment]
Issue should be resolved after https://github.com/DSD-DBS/capella-dockerimages/pull/198 is merged

**Comment by dominik003** [comment]
Resolved by https://github.com/DSD-DBS/capella-dockerimages/pull/198
