### ISSUE TITLE
Dynamically rebalance sessions in training mode

### ISSUE THREAD

**Issue by dominik003** [DSD-DBS/capella-collab-manager#982]
In the session viewer, when two sessions are open side-by-side, users should have the ability to dynamically resize or rebalance the screen space allocated to each session. This feature could be implemented by incorporating a slider between the two sessions, allowing users to easily move it left or right to adjust the balance between the sessions. A challenge to address is how to handle scenarios where the slider is moved entirely to one side, effectively allocating all the available space to a single session. A potential solution could be to automatically collapse the session when its size becomes too small (see #985 for collapsing of sessions).

**Comment by MoritzWeber0** [comment]
This feature should be part of the training mode, not the "flexible" session viewer, more information: https://github.com/DSD-DBS/capella-collab-manager/issues/983#issuecomment-1706063605

**Comment by MoritzWeber0** [comment]
Depends on https://github.com/DSD-DBS/capella-collab-manager/issues/990
