### ISSUE TITLE
Remove drag and drop of sessions in training mode

### ISSUE THREAD

**Issue by dominik003** [DSD-DBS/capella-collab-manager#983]
In the session viewer, we are primarily focused on supporting up to two sessions at the same time, specifically Capella and Jupyter. Given this limitation, the ability to move sessions around is not necessary. By eliminating this option, it may simplify future enhancements and make them easier to implement.

**Comment by MoritzWeber0** [comment]
I'd not remove the current drag&drop feature. Instead, there should be two different layout modes: 

1. Training Mode: The training mode has a fixed layout. Sessions can be rebalanced via sliders. There is no drag&drop. 
2. Session viewer: The session viewer has a flexible layout, offering typical window manager features. Drag&drop, resizing of individual windows and minimizing / maximizing would be features of the session viewer.

**Comment by MoritzWeber0** [comment]
Tracked in https://github.com/DSD-DBS/capella-collab-manager/issues/990 instead.
