### ISSUE TITLE
Focus sessions in training mode

### ISSUE THREAD

**Issue by dominik003** [DSD-DBS/capella-collab-manager#985]
When two sessions are open in the training mode, users should have the option to collapse one session, allowing the other to occupy the entire screen, effectively creating a "focus mode." The collapsed session could remain accessible through a minimal sidebar, which when clicked, would uncollapse and restore the session to its original size.

**Comment by MoritzWeber0** [comment]
The main purpose of collapsing sessions is to focus other sessions (as far as I can read if from your description). Therefore, I would not add a feature to collapse sessions. Instead, there should be button to focus a session (which maximizes to full-screen then). When the user wants to get back to the initial view, he/she can click a button to get back to the initial view (disable max. mode).

**Comment by MoritzWeber0** [comment]
Depends on https://github.com/DSD-DBS/capella-collab-manager/issues/990
